tap "colindean/fonts-nonfree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ack"
brew "antigen"
brew "brew-cask-completion"
brew "coreutils"
brew "dnsmasq"
brew "flow"
brew "git"
brew "git-flow"
brew "go"
brew "imagemagick"
brew "lastpass-cli"
brew "mas"
brew "node"
brew "newman"
brew "pandoc"
brew "pre-commit"
brew "pyenv"
brew "rbenv"
brew "rsync"
brew "ruby"
brew "unrar"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"
cask "abstract"
cask "adobe-creative-cloud"
cask "adobe-digital-editions"
cask "airtable"
cask "alfred"
cask "appcleaner"
cask "audio-hijack"
cask "authy"
cask "backblaze"
cask "bartender"
cask "brave-browser"
cask "cardhop"
cask "charles"
cask "cheatsheet"
cask "dropbox"
cask "droplr"
cask "font-fira-code"
cask "font-fontawesome"
cask "font-heebo"
cask "font-microsoft-office"
cask "gas-mask"
cask "go2shell"
cask "google-chrome"
cask "handbrake"
cask "hazel"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "kaleidoscope"
cask "keyboard-maestro"
cask "keycastr"
cask "kindle"
cask "krisp"
cask "lastpass"
cask "microsoft-auto-update"
cask "microsoft-outlook"
cask "microsoft-teams"
cask "miro"
cask "parallels"
cask "pock"
cask "post-haste"
cask "postman"
cask "raindropio"
cask "rocket"
cask "sequel-pro"
cask "sketch"
cask "slack"
cask "soundsource"
cask "teamviewer"
cask "the-unarchiver"
cask "thingsmacsandboxhelper"
cask "transmit"
cask "visual-studio-code"
cask "vlc"
cask "waves-central"
cask "webpquicklook"
cask "yt-music"
mas "Better Rename 9", id: 414209656
mas "com.apptorium.Workspaces", id: 1219826448
mas "Core Tunnel", id: 1354318707
mas "Crypto Pro", id: 980888073
mas "Delay-Start", id: 591620786
mas "Drafts", id: 1435957248
mas "Fantastical", id: 975937182
mas "Flow", id: 1423210932
mas "Growl", id: 467939042
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "PCalc", id: 403504866
mas "SiteSucker", id: 442168834
mas "Spark", id: 1176895641
mas "StuffIt Expander", id: 919269455
mas "Things", id: 904280696
mas "ToothFairy", id: 1191449274
mas "Tweetbot", id: 1384080005
mas "Typeface", id: 1062679359
mas "Webcam Settings", id: 533696630
mas "Xcode", id: 497799835
